- cmplibrary/build.gradle
- cmplibrary/src/main/java/com/sourcepoint/cmplibrary/ConsentLib.java
- cmplibrary/src/main/java/com/sourcepoint/cmplibrary/SourcePointClientBuilder.java
[The IAB Consent SDK only supports Java 8 and above](https://github.com/InteractiveAdvertisingBureau/Consent-String-SDK-Java/issues/21). 
[There's a port of it to Android](https://github.com/didomi/Consent-String-SDK-Android)
In this PR we change from the former SDK to the latter.
> use com.iab.gdpr_android rather than com.iab.gdpr Consent String SDK

- CHANGELOG.md
- app/src/main/java/com/example/dmitrirabinowitz/test_project/MainActivity.java
- cmplibrary/build.gradle
- cmplibrary/src/main/java/com/sourcepoint/cmplibrary/ConsentLib.java
- cmplibrary/src/main/java/com/sourcepoint/cmplibrary/ConsentLibBuilder.java
TL;DR; If you want us to show and hide the Privacy Manager in your views, call the `setViewGroup` passing a view and we'll manage the rest. Otherwise, you'll have to add and remove the `ConsentLib#webView` when you see best fit.
Previously, if `viewGroup` was null we'd get the Activity's content screen and attach the `WebView` to it. In order to give more flexibility on how and when the `WebView` should be displayed, we only attach it to the `viewGroup` if one is given. Otherwise, it'll be up to the app to decide what to do with the `WebView`.
> Render `webview` if `viewGroup` is given

- app/src/main/java/com/example/dmitrirabinowitz/test_project/MainActivity.java
- cmplibrary/src/main/java/com/sourcepoint/cmplibrary/ConsentLib.java
- cmplibrary/src/main/java/com/sourcepoint/cmplibrary/ConsentLibBuilder.java
- cmplibrary/src/main/java/com/sourcepoint/cmplibrary/SourcePointClient.java
With this PR we make possible for the user to switch between the "old" and "new" Privacy Manager, before it's completely rolled out.
> enable new PM

- cmplibrary/src/main/java/com/sourcepoint/cmplibrary/ConsentLib.java
- cmplibrary/src/main/java/com/sourcepoint/cmplibrary/ConsentLibBuilder.java
In response to #49, in this PR we check if the `activity` is not `null` or `finishing()` before calling `runOnUIThread` on it.
> Check for null activity

- cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/GDPRConsentLib.java
Double assuring we call onError for this async case. Based on a fix request by Sound Cloud.
> call onError from goBackInAnotherThread

- CHANGELOG.md
- README.md
- cmplibrary/build.gradle
- cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/GDPRConsentLib.java
- cmplibrary/src/test/java/com/sourcepoint/gdpr_cmplibrary/GDPRConsentLibTest.java
Without the `site_id` query param, the PM will work only for properties that don't belong to property groups. 
If the `site_id` query param is missing and the property is a grouped property, the PM will try to load the "default" PM from that group which is not always the correct one.
> SP-3813 add property id to pm url (as site_id query param)

- cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/GDPRUserConsent.java
If the `VendorGrant` class is not public we can't access its values like:
```java
VendorGrant vendorGrant = consent.vendorGrants.get("5e4a5fbf26de4a77922b38a6");
if (vendorGrant != null && vendorGrant.vendorGrant) {
// vendor is granted
} else {
// vendor is not granted
}
```
> make VendorGrant public

- AutomationFramework/README.md
- AutomationFramework/src/main/java/org/framework/retryAnalyzer/RetryAnalyzer.java
- AutomationFramework/src/main/java/org/framework/retryAnalyzer/RetryListener.java
- AutomationFramework/src/main/resources/testng.xml
Implement retry logic to re-run failed tests before declaring as actual failure. For MetaApp testing currently we are considering max 3 as retry count for failed test to re-execute.
> SP-4221 retry logic to run failed tests

- app/src/main/java/com/sourcepoint/example_app/MainActivity.java
- cmplibrary/src/main/res/raw/js_receiver.js
- cmplibrary/src/test/JS/js_receiver.test.js
@leodoin if it weren't by the js_receiver.test this PR would take much longer to be done and probably would contain errors hard to catch as well. 
Fun fact of the day 💡
If we use `//` as comments in the `js_receiver` it will prevent the message from rendering with my DNS configuration.
When changing that to `/* */` style, the message would start rendering again... 🤯
> SP-4544 avoid logging js errors

- cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/ConsentLibBuilder.java
this fix app crashing (if no external Browser) when the callback is not set
> make `onNoIntentActivitiesFound` optional

- cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/ConsentAction.java
- cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/ConsentWebView.java
- cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/GDPRConsentLib.java
- cmplibrary/src/main/res/raw/js_receiver.js
- cmplibrary/src/test/java/com/sourcepoint/gdpr_cmplibrary/ConsentActionTest.java
- cmplibrary/src/test/java/com/sourcepoint/gdpr_cmplibrary/GDPRConsentLibTest.java
- In Web message sending “consentLanguage” param in sendConsent API call, this param is captured from action event.
- In Native message sending Locale.getDefault().getLanguage() value as consentLanguage param.
> [SP-5295] Add support for consent language

- cmplibrary/src/main/res/raw/js_receiver.js
This [commit](https://github.com/SourcePointUSA/android-cmp-app/commit/a6d55dd0b5b036d21286d867a9620a249b663148#diff-ce030a4d361f277c06221d3ab31a229651bd8afc2453df5756a7dfb4488af10bR11) introduced a regression to the JSReceiver causing it to throw error on Android API 22 and below. 
This PR fixes this issue and refactors the code.
> SP-5259 remove es6 from js_receiver

- cmplibrary/src/main/assets/js_receiver.js
Add `customActionId` to PM's action payload to fully support custom action coming from PM
https://sourcepoint.atlassian.net/browse/DIA-1391
PS: @carmelo-iriti after merging, can you make sure to merge into v7 as well? So those changes won't be lost in the new version of the SDK.
> [DIA-1391] Add customActionId to pm action payload

- cmplibrary/src/main/java/com/sourcepoint/cmplibrary/model/exposed/SPConsents.kt
**JIRA Ticket** - https://sourcepoint.atlassian.net/browse/DIA-2106
**Description**
This PR introducing exposure of UUID for CCPAConsent object, which leads to our users be able to use UUID of CCPA.
> [DIA-2106] Make UUID public on CCPAConsent

- cmplibrary/src/test/java/com/sourcepoint/cmplibrary/model/SPConsentsTest.kt
Jira - https://sourcepoint.atlassian.net/browse/DIA-2210
This PR introduces regression tests that cover the exposure of UUID of CCPA and GDPR via CCPAConsent and GDPRConsent accordingly. Those tests will fail if we decide to protect UUID.
> [DIA-2210] Create a regression test for DIA-2106

- cmplibrary/src/main/java/com/sourcepoint/cmplibrary/data/ServiceImpl.kt
- cmplibrary/src/main/java/com/sourcepoint/cmplibrary/data/network/model/optimized/MessagesApiModelExt.kt
- cmplibrary/src/main/java/com/sourcepoint/cmplibrary/data/network/model/optimized/MetaDataApiModel.kt
This PR removes data from the metadata query param to the meta-data endpoint. The data removed is harming our ability to cache meta-data response, thus increasing our costs and response times.
> DIA-2452 remove unnecessary query params from meta-data

- cmplibrary/src/main/java/com/sourcepoint/cmplibrary/SpConsentLibImpl.kt
- cmplibrary/src/main/java/com/sourcepoint/cmplibrary/data/Service.kt
- cmplibrary/src/main/java/com/sourcepoint/cmplibrary/data/ServiceImpl.kt
- cmplibrary/src/test/java/com/sourcepoint/cmplibrary/data/ServiceImplTest.kt
Jira Ticket - [DIA-2449](https://sourcepoint.atlassian.net/browse/DIA-2449)
This PR introduces a change to dealing with `onError()` callback from the message flow. Whenever there are an error in `postPvData` network call, the SDK **should not** invoke the `onError()` callback, but **should** onvoke all the other in-app metrics.
[DIA-2449]: https://sourcepoint.atlassian.net/browse/DIA-2449?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DIA-2449] Not call onError if pv-data fails

- samples/metaapp/src/main/AndroidManifest.xml
Jira - [DIA-3253](https://sourcepoint.atlassian.net/browse/DIA-3253)
Description - accidentally removed `<activity>` in `AndroidManifest.xml`
[DIA-3253]: https://sourcepoint.atlassian.net/browse/DIA-3253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DIA-3253] MetaApp crash fix

- cmplibrary/src/main/java/com/sourcepoint/cmplibrary/consent/ConsentManagerUtils.kt
- cmplibrary/src/main/java/com/sourcepoint/cmplibrary/creation/Builder.kt
- cmplibrary/src/main/java/com/sourcepoint/cmplibrary/creation/Factory.kt
- cmplibrary/src/test/java/com/sourcepoint/cmplibrary/consent/ConsentManagerUtilsImplTest.kt
Was investigating an issue regarding GDPR's `legalBasisChangeDate` and stumbled on a bunch of unused code in the SDK. This PR removes it, tests (should) still pass.
> remove unused code from ConsentManagerUtils

- cmplibrary/src/main/java/com/sourcepoint/cmplibrary/data/network/model/optimized/includeData/IncludeData.kt
- cmplibrary/src/test/java/com/sourcepoint/cmplibrary/data/network/model/optimized/includeData/IncludeDataKtTest.kt
`translateMessage` should only be used with platforms that don't rely on the rendering app for translating the message (ie. tvOS and Roku)
> remove translateMessage from includeData

- cmplibrary/src/main/java/com/sourcepoint/cmplibrary/data/ServiceImpl.kt
- samples/app/src/androidTest/java/com/sourcepoint/app/v6/MainActivityKotlinTest.kt
- samples/app/src/main/java/com/sourcepoint/app/v6/MainActivityKotlin.kt
Fix an issue causing the consent object being empty if the user takes a consent action where the legislation `applies` field is `false`.
> DIA-4068 fix consent empty on applies false

- cmplibrary/src/main/java/com/sourcepoint/cmplibrary/model/exposed/SPConsents.kt
Hi there,
in our flutter app we would like to read out the webConsents ourselves, so we can inject them manually.
For this we need to access `SPConsents.toWebViewConsentsJsonObject()`
This change is analogous to the change recently applied to the iOS sdk (https://github.com/SourcePointUSA/ios-cmp-app/pull/560)
With this change it would allow feature parity in iOS vs android within the source point flutter plugin I'm working on at https://github.com/thekorn/sourcepoint_unified_cmp
Does it make sense?
thanks for your support
Have a nice day
Markus
> feat: make SPConsents.toWebViewConsentsJsonObject() public

- cmplibrary/src/androidTest/java/com/sourcepoint/cmplibrary/campaign/CampaignManagerImplTest.kt
- samples/metaapp/src/main/java/com/sourcepointmeta/metaapp/ui/property/AddUpdatePropertyFragment.kt
[DIA-4713](https://sourcepoint.atlassian.net/browse/DIA-4713) Key Value Pairs do not appear to save on Meta App version 7.11.0
[DIA-4713]: https://sourcepoint.atlassian.net/browse/DIA-4713?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DIA-4713 Change `setView` argument for key-value pairs in meta-app

- cmplibrary/src/main/java/com/sourcepoint/cmplibrary/mobile_core/SPConsentWebView.kt
[DIA-5502](https://sourcepoint.atlassian.net/browse/DIA-5502) [AndroidTv] Navigation Broken on 7.12.0
[DIA-5502]: https://sourcepoint.atlassian.net/browse/DIA-5502?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DIA-5502] Fix AndroidTv navigation 

- README.md
- cmplibrary/src/main/java/com/sourcepoint/cmplibrary/SpConsentLib.kt
- cmplibrary/src/main/java/com/sourcepoint/cmplibrary/SpConsentLibMobileCore.kt
- cmplibrary/src/main/java/com/sourcepoint/cmplibrary/creation/Factory.kt
- cmplibrary/src/main/java/com/sourcepoint/cmplibrary/creation/SpCmpBuilder.kt
- cmplibrary/src/main/java/com/sourcepoint/cmplibrary/creation/SpConfigDataBuilder.kt
- cmplibrary/src/main/java/com/sourcepoint/cmplibrary/mobile_core/PMUrlBuilder.kt
- cmplibrary/src/main/java/com/sourcepoint/cmplibrary/mobile_core/SPConsentWebView.kt
- samples/app/build.gradle
- samples/app/src/androidTest/java/com/sourcepoint/app/v6/MainActivityKotlinTest.kt
- samples/app/src/androidTest/java/com/sourcepoint/app/v6/TestUseCase.kt
- samples/app/src/main/java/com/sourcepoint/app/v6/MainActivityKotlin.kt
- samples/app/src/main/java/com/sourcepoint/app/v6/di/AppModule.kt
Now when `dismissMessageOnBackPress = false` the SDK won't dismiss the message when the back button is pressed. This value is `true` by default, ie. sdk dismisses the message by default.
> DIA-5417 add `dismissMessageOnBackPress` setting

- cmplibrary/build.gradle.kts
- cmplibrary/src/main/java/com/sourcepoint/cmplibrary/data/network/util/CampaignType.kt
- cmplibrary/src/main/java/com/sourcepoint/cmplibrary/mobile_core/PMUrlBuilder.kt
- samples/app/src/androidTest/java/com/sourcepoint/app/v6/TestUseCase.kt
- samples/app/src/main/java/com/sourcepoint/app/v6/MainActivityKotlin.kt
- samples/app/src/main/java/com/sourcepoint/app/v6/core/DataProvider.kt
- samples/app/src/main/java/com/sourcepoint/app/v6/di/AppModule.kt
- samples/app/src/main/res/layout/activity_main_v7.xml
- samples/app/src/main/res/values/strings.xml
[DIA-5863](https://sourcepoint.atlassian.net/browse/DIA-5863)
[Mobile] loadPreferenceCenter missing from SDKs
[DIA-5863]: https://sourcepoint.atlassian.net/browse/DIA-5863?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DIA-5863 add `loadPreferenceCenter` function

- cmplibrary/src/main/java/com/sourcepoint/cmplibrary/util/WebViewUtils.kt
[DIA-5916](https://sourcepoint.atlassian.net/browse/DIA-5916)
Links in WebView to Launch Phone Dialer on Android Not Working
[DIA-5916]: https://sourcepoint.atlassian.net/browse/DIA-5916?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DIA-5916 phone dialer link handling

- README.md
- cmplibrary/src/main/assets/js_receiver.js
- cmplibrary/src/main/java/com/sourcepoint/cmplibrary/SpClient.kt
- cmplibrary/src/main/java/com/sourcepoint/cmplibrary/SpConsentLibMobileCore.kt
- cmplibrary/src/main/java/com/sourcepoint/cmplibrary/mobile_core/SPConsentWebView.kt
- samples/app/src/main/java/com/sourcepoint/app/v6/MainActivityJava.java
- samples/app/src/main/java/com/sourcepoint/app/v6/MainActivityKotlin.kt
The message builder for Preferences messages, now has a setting to add a timeout to dispatch an event in case the user is inactive for X seconds.
When this happens, the rendering app dispatches the event `sp.userInactive` and the SDK ultimately calls the new callback `onMessageInactivityTimeout`.
> DIA-5954 implement `onMessageInactivityTimeout ` callback

- cmplibrary/build.gradle.kts
- integration_tests/build.gradle.kts
- samples/app/build.gradle
- ui-test-util/build.gradle
Removing `coreLibraryDesugaring` since it's no longer needed. It affects performance, compatibility and bundle size of our SDK.
> remove isCoreLibraryDesugaring

- cmplibrary/src/main/java/com/sourcepoint/cmplibrary/model/exposed/SPConsents.kt
[DIA-5970](https://sourcepoint.atlassian.net/browse/DIA-5970)
[P3] [Android] expose gdpr `dateCreated` field
[DIA-5970]: https://sourcepoint.atlassian.net/browse/DIA-5970?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DIA-5970] Expose `gdpr` `dateCreated` field

- build.gradle
- cmplibrary/build.gradle.kts
- cmplibrary/src/main/java/com/sourcepoint/cmplibrary/SpConsentLib.kt
- cmplibrary/src/main/java/com/sourcepoint/cmplibrary/legacy/TransferFromNativeSDK.kt
- integration_tests/src/androidTest/java/com/sourcepoint/cmplibrary/legacy/LegacyStateTest.kt
- integration_tests/src/androidTest/java/com/sourcepoint/cmplibrary/legacy/SharedPrefsImporter.kt
- samples/metaapp/build.gradle.kts
Authenticated consent seems to be working only on instances of the SDK that have had `loadMessages` called with `authId`. 
If another instance of the SDK is then initialized, that instance of the SDK won't have the value stored for `authId` and consent actions (from the PM for example), won't be stored for that `authId`. 
This PR and https://github.com/SourcePointUSA/mobile-core/pull/78 fixes this issue.
> DIA-6098 fix `authId` multiple instances
