CHANGELOG.md
app/build.gradle
cmplibrary/build.gradle
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/ConsentLib.java
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/SourcePointClient.java
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/SourcePointClientBuilder.java

Fix api lt 26 bugs

---

cmplibrary/src/main/java/com/sourcepoint/cmplibrary/ConsentLibBuilder.java
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/ConsentLibNoOP.java

implement a no operation ConsentLib if API level < 19

---

CHANGELOG.md
app/src/main/java/com/example/dmitrirabinowitz/test_project/MainActivity.java
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/ConsentLib.java
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/ConsentLibBuilder.java

* rename `willShowMessage` to `onMessageReady`
* call `onMessageReady` on `onReceiveMessageData`
* add `ConsentLib#willShowMessage` boolean field

Rename message will show callback

---

CHANGELOG.md
cmplibrary/build.gradle
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/ConsentLib.java
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/ConsentWebView.java

* Extracted away the `WebView` setup into `ConsentWebView`.
* Fix a bug that'd prevent the WebView from loading the first time on Android > 19

Fix WebView not loading for api > 19

---

cmplibrary/src/main/java/com/sourcepoint/cmplibrary/ConsentLib.java
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/ConsentWebView.java

* add timeout threshold
* set accept javascript before adding JavascriptInterface

refactor ConsentWebView

---

app/src/main/java/com/example/dmitrirabinowitz/test_project/MainActivity.java
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/ConsentLib.java
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/ConsentLibBuilder.java

1. added configurable message time out feature.

SP-1481 Add configurable timeout

---

cmplibrary/build.gradle
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/ConsentLib.java

Details merge request
1. added null check on activity reference SP-1496
2. canceled timer before releasing webview reference in destroy method SP-1500

change details

---

cmplibrary/src/main/java/com/sourcepoint/cmplibrary/ConsentWebView.java

When a link contain an image within:
```html
<a href="...">Click me <img src="..." /></a>
```
the WebView for some reason decides to open the image in the browser instead of the link url.
In this PR we fix this issue.

fix webview opening image instead of link url

---

CHANGELOG.md
README.md
app/src/main/java/com/sourcepoint/test_project/MainActivity.java
build.gradle
cmplibrary/build.gradle
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/ConsentWebView.java
gradle.properties
gradle/wrapper/gradle-wrapper.properties

fix performance and security issue

---

cmplibrary/src/main/java/com/sourcepoint/cmplibrary/ConsentLib.java

fix null pointer exception on webview display

---

cmplibrary/src/main/java/com/sourcepoint/cmplibrary/ConsentLib.java

When the user clicks on an "option" inside the message, the callback method `onMessageChoiceSelect` is called and the attribute `ConsentLib.choiceType` is set to one of the `MESSAGE_OPTIONS`. We get an integer from the client js and we map those integers into one of the `MESSAGE_OPTIONS` enum.
At the moment, there're only two options mapped:
```
12 -> SHOW_PRIVACY_MANAGER
Any -> UNKNOWN
```
For an example on how the `onMessageChoiceSelect` can be used, refer to https://github.com/SourcePointUSA/android-cmp-app/wiki/How-to-setup-a-%22top-bottom-only%22-kind-of-message.

add MESSAGE_OPTIONS enum to ConsentLib

---

cmplibrary/src/main/java/com/sourcepoint/cmplibrary/ConsentLib.java

implemented isEmpty() check on euconsent string.

check whther euconsent string isEmpty to avoid background crash.

---

cmplibrary/src/main/java/com/sourcepoint/cmplibrary/SourcePointClient.java

This implementation will now send error back to user if there are any failures while having api calls.

onFailure implementation for api calls

---

cmplibrary/build.gradle
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/ConsentLib.java
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/SourcePointClient.java
cmplibrary/src/test/java/com/sourcepoint/cmplibrary/ConsentLibBuilderTest.java
cmplibrary/src/test/java/com/sourcepoint/cmplibrary/EncodedParamTest.java
cmplibrary/src/test/java/com/sourcepoint/cmplibrary/SourcePointClientBuilderTest.java
cmplibrary/src/test/java/com/sourcepoint/cmplibrary/SourcePointClientTest.java

now gdpr status check in repeated each time SDK is initialized.

Repeat gdpr status check

---

cmplibrary/build.gradle
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/SourcePointClient.java
cmplibrary/src/test/java/com/sourcepoint/cmplibrary/ConsentLibBuilderTest.java
cmplibrary/src/test/java/com/sourcepoint/cmplibrary/EncodedParamTest.java
cmplibrary/src/test/java/com/sourcepoint/cmplibrary/SourcePointClientBuilderTest.java
cmplibrary/src/test/java/com/sourcepoint/cmplibrary/SourcePointClientTest.java

implemented unit test cases for SDK

implemented unit test cases for SDK

---

CHANGELOG.md
README.md
app/src/main/java/com/sourcepoint/test_project/MainActivity.java
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/Consent.java
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/ConsentLib.java
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/ConsentLibBuilder.java
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/ConsentWebView.java
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/SourcePointClient.java
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/SourcePointClientBuilder.java

1. passing siteId and pmId at the time of construction
2. set isShowPM to true to see privacy manager directly
3. New script callback implementations

Integrate new message script & PrivacyManager initialisation

---

cmplibrary/build.gradle
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/ConsentLib.java
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/ConsentWebView.java
cmplibrary/src/test/java/com/sourcepoint/cmplibrary/ConsentLibTest.java

cleared all consent data on error occurred event

cleared all consent data on error occurred event

---

.idea/modules.xml
authexample/src/main/java/com/example/authexample/ConsentManager.java
authexample/src/main/java/com/example/authexample/HomeActivity.java
metaapp/build.gradle

* update authexample with latest SDK
* fix build.gradle file

Fix authexample build

---

cmplibrary/build.gradle
cmplibrary/src/main/AndroidManifest.xml
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/ConsentLib.java
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/ConsentLibBuilder.java

Logged error along with property details to see rollbar dashbar

implemented rolbar analytics tool

---

cmplibrary/build.gradle
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/ConsentLib.java

changes in this PR
1. release activity reference in consentLIb on destroy method.
2. remove and add webview to parent viewGroup in display webview method (already implemented in 3.x.x)
3. change android SDK version in build.gradle to 2.4.5

Memory leak sdk fix

---

metaapp/src/main/java/com/sourcepointmeta/app/database/entity/TargetingParam.java

Removed warnings from metaapp

---

cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/GDPRConsentLib.java
cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/GDPRUserConsent.java
cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/NativeMessage.java
cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/NativeMessageAttrs.java

* font size fixed (now user can see different font sizes on the screen)
* crash on msg dismiss at first launch fixed
* can receive font size as int from msgJSON

Native msg font size as int

---

cmplibrary/build.gradle
cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/GDPRConsentLib.java
cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/SourcePointClient.java
cmplibrary/src/test/java/com/sourcepoint/gdpr_cmplibrary/ConsentLibExceptionTest.java
cmplibrary/src/test/java/com/sourcepoint/gdpr_cmplibrary/ConsentWebViewTest.java
cmplibrary/src/test/java/com/sourcepoint/gdpr_cmplibrary/GDPRConsentLibTest.java
cmplibrary/src/test/java/com/sourcepoint/gdpr_cmplibrary/NativeMessageTest.java
cmplibrary/src/test/java/com/sourcepoint/gdpr_cmplibrary/SourcePointClientTest.java
cmplibrary/src/test/java/com/sourcepoint/gdpr_cmplibrary/StoreClientTest.java

Added unit test with mock webserver for GDPR Android SDK API .
Refactored tests in GDPRConsentLib and ConsentWebView class.
Added tests for ConsentLibExcepton class.
Added remaining tests to StoreClient class.

Sdk unit tests modify

---

cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/GDPRConsentLib.java
cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/StoreClient.java

Fixes https://sourcepoint.atlassian.net/browse/SP-3253

Store IAB data on get message

---

.gitignore
app/src/main/java/com/sourcepoint/test_project/MainActivity.java
app/src/main/java/com/sourcepoint/test_project/PropertyConfig.java
app/src/main/res/raw/mobile_demo.json

*** no changes on the consent lib itself ***

Property config tcfv2 for example app

---

.gitignore
app/src/main/java/com/sourcepoint/test_project/MainActivity.java
app/src/main/java/com/sourcepoint/test_project/PropertyConfig.java
app/src/main/res/raw/a_demo_property.json

file config added to example app
*** no changes to the SDK ***

[TCFv1] Property config file added to example app

---

cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/ConsentWebView.java

Updated javascript injection logic from onPagefinished to onPageStarted

fix PM not loading on first app launch [SP-3194]

---

authexample/src/main/java/com/example/authexample/ConsentManager.java
authexample/src/main/java/com/example/authexample/HomeActivity.java
authexample/src/main/java/com/example/authexample/LoginActivity.java
authexample/src/main/java/com/example/authexample/PropertyConfig.java
authexample/src/main/res/layout/activity_login.xml
authexample/src/main/res/raw/mobile_demo_web.json

fixed uthExample to support SDK v5

fixed authExample for sdk v5

---

cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/ConsentWebView.java

Implemented redirection link urls in external browser.

implemented redirection link url in external browser. - TCFv1

---

cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/ConsentWebView.java

Implemented redirection of url on external browser

SP-3477_open_link_on_external_browser_TCFv2

---

cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/ConsentWebView.java
cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/GDPRConsentLib.java

implemented onBack pressed dismiss action tcfv1

SP-3436 dismiss action on back press TCFv1

---

cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/ConsentAction.java
cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/ConsentWebView.java
cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/GDPRConsentLib.java

implemented on back button press dismiss action

SP-3436 dismiss action on back button press within message - TCFv2

---

cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/StoreClient.java
cmplibrary/src/test/java/com/sourcepoint/gdpr_cmplibrary/StoreClientTest.java

Remove all IAB related data before storing new one.

[SP-3372] flush TCData on StoreClient.setTCData

---

cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/GDPRConsentLib.java

Released activity reference on error.

SP-3498 release activity reference on error

---

cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/GDPRConsentLib.java

fixed consent persistence for pm as first layer message

SP-3517 fixed consent persistence for pm as first layer message

---

metaapp/build.gradle
metaapp/src/main/java/com/sourcepointmeta/app/SourcepointApp.java

MetaApp support from Android API 16

SP-3104 MetaApp support from Android API 16 tcfv2

---

cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/GDPRConsentLib.java
cmplibrary/src/test/java/com/sourcepoint/gdpr_cmplibrary/ConsentWebViewTest.java
cmplibrary/src/test/java/com/sourcepoint/gdpr_cmplibrary/GDPRConsentLibTest.java

Added network connection check before making http call and loading url

Sp 3616 check intenet connection

---

CHANGELOG.md
cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/ConsentLibBuilder.java

fixed targeting pram not showing message issue.

SP 3687 unable to see message with targeting param

---

cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/GDPRUserConsent.java

fixed example crash due to empty userconsent object

SP-3686 example crash due to empty userconsent object

---

CHANGELOG.md
cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/ConsentLibBuilder.java
cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/ConsentLibException.java
cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/ConsentWebView.java
cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/GDPRConsentLib.java
cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/SourcePointClient.java
cmplibrary/src/test/java/com/sourcepoint/gdpr_cmplibrary/ConsentLibExceptionTest.java
cmplibrary/src/test/java/com/sourcepoint/gdpr_cmplibrary/GDPRConsentLibTest.java

Implemented network connection check before making http call and loading url in webview

SP 3657 check internet connection tcfv2

---

gradle.properties
metaapp/src/main/res/values/strings.xml

Updated appname TCFv1_GDPR-MetaApp.apk

SP-3753 Added prefix TCFv1 to metaApp apk name

---

cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/GDPRConsentLib.java

ensured onConsentReady callback at message cancel and pm cancel event

SP-3633 ensure onConsentReady callback at message cancel and pm cancel event

---

metaapp/src/main/java/com/sourcepointmeta/app/ui/ConsentViewActivity.java
metaapp/src/main/java/com/sourcepointmeta/app/ui/NewPropertyActivity.java

Increased timeout duration to 30 seconds

Increased timeout duration to 30 seconds

---

metaapp/src/main/java/com/sourcepointmeta/app/ui/NewPropertyActivity.java

fixed metaApp create new property flow.

---

cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/ConsentWebView.java

SP-3836 fix android lollipop webview crash

---

cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/GDPRConsentLib.java

- add try/catch blocks to async calls

SP-3835 try/catch block to async calls

---

app/src/main/java/com/sourcepoint/example_app/MainActivity.java
cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/ConsentLibBuilder.java
cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/ConsentWebView.java
cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/GDPRConsentLib.java
cmplibrary/src/main/res/raw/js_receiver.js
cmplibrary/src/test/java/com/sourcepoint/gdpr_cmplibrary/ConsentWebViewTest.java
cmplibrary/src/test/java/com/sourcepoint/gdpr_cmplibrary/GDPRConsentLibTest.java

Added  pmWillShow , pmDidDisappear, messageWillShow and messageDidDisappear lifecycle methods.

SP 3197 implement lifecycle methods from iOS

---

metaapp/src/main/java/com/sourcepointmeta/app/common/Constants.java
metaapp/src/main/java/com/sourcepointmeta/app/ui/ConsentViewActivity.java
metaapp/src/main/java/com/sourcepointmeta/app/ui/NewPropertyActivity.java

fixed metaApp flow while creating new property and increased default timeout to 30 sec

Fixed MetaApp flow and increased default timeout to 30 sec.

---

cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/StoreClient.java
cmplibrary/src/test/java/com/sourcepoint/gdpr_cmplibrary/StoreClientTest.java

Modified gtTCData method to get right primitiv value from sharedPref
Added unit tests to verify tcdata with premitives
Removed constants from StoreClientTest file.

SP-3790 Modified getTCData method and added tests for tcdata

---

cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/NativeMessage.java

SP-4082 all native message buttons made public

---

cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/ConsentWebView.java

set flag to intent FLAG_ACTIVITY_NEW_TASK while opening external links in external browser.

SP-4115 set flag to intent as new task TCFv2.

---

cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/ConsentWebView.java

set flag to intent FLAG_ACTIVITY_NEW_TASK while opening external links in external browser.

SP-4115 Set flag for new task

---

.gitignore
AutomationFramework/src/main/java/org/framework/helpers/Page.java
AutomationFramework/src/main/java/org/framework/pageObjects/ConsentViewPage.java
AutomationFramework/src/main/java/org/framework/pageObjects/NewSitePage.java
AutomationFramework/src/main/java/org/framework/pageObjects/PrivacyManagerPage.java
AutomationFramework/src/main/java/org/framework/pageObjects/SiteDebugInfoPage.java
AutomationFramework/src/main/java/org/framework/pageObjects/SiteListPage.java
AutomationFramework/src/main/java/tests/GDPR_TCFV2_MetaAppTests.java
AutomationFramework/src/main/resources/androidDevice.json

- Refactor code to remove use of Thread.sleep
- Removed syytem.out lines
- Implement explicitly wait method to wait till the expected elements displayed
- Implement log messaging system

[SP-4077] Removed Thread.sleep and used explicitly wait method and implement log messages

---

cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/ConsentLibBuilder.java
cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/GDPRConsentLib.java
cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/UIThreadHandler.java
cmplibrary/src/test/java/com/sourcepoint/gdpr_cmplibrary/GDPRConsentLibTest.java

Here we encapsulate the uiThreadHandler in our own custom handler so we can enable/disable it as we wish.
I hope you guys like this idea as much as I do ❤️

Make ui thread handler disable programatically

---

cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/ConsentLibBuilder.java
cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/ConsentWebView.java
cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/GDPRConsentLib.java

[SP-4122] Revert back button action override

---

.github/workflows/CreateJiraTicket.yml
.github/workflows/test.yml
app/build.gradle
app/src/main/AndroidManifest.xml
authexample/build.gradle
cmplibrary/build.gradle
cmplibrary/src/test/java/com/sourcepoint/gdpr_cmplibrary/ConsentActionTest.java
metaapp/build.gradle

After this PR is merged we'll be able to:
* run unit tests on every PR and when merging to `develop` branch
* have jira tickets created/labelled automatically when somebody creates an issue via GitHub

SP-4178 run unit tests on GitHub actions

---

cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/GDPRUserConsent.java
cmplibrary/src/test/java/com/sourcepoint/gdpr_cmplibrary/GDPRUserConsentTest.java

Added unit tests for GDPRUserConsent class
checked state of fields after fetching it from local storage.

SP-4021 Added unit tests for GSPRUserConsent class

---

cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/SourcePointClient.java
cmplibrary/src/test/java/com/sourcepoint/gdpr_cmplibrary/SourcePointClientTest.java

Implemented okhttp client mock

[SP-3596] Unit tests for SourcePointcClient class by mocking okhttp client

---

build.gradle
cmplibrary/build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties
metaapp/build.gradle
metaapp/src/main/java/com/sourcepointmeta/app/SourcepointApp.java

Updated gradle version to 6.5.1 and android gradle plugin version to 4.0.1.

SP-3434 Update gradle plugin 

---

cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/ConsentLibBuilder.java
cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/SourcePointClientConfig.java
cmplibrary/src/test/java/com/sourcepoint/gdpr_cmplibrary/ConsentLibBuilderTest.java
cmplibrary/src/test/java/com/sourcepoint/gdpr_cmplibrary/SourcePointClientTest.java

Removed setInternalStage() method.

SP-4418 Refactor consent lib builder class

---

cmplibrary/src/main/res/raw/js_receiver.js
cmplibrary/src/test/JS/js_receiver.test.js
cmplibrary/src/test/JS/test_config.js

[hotfix] prevent resize event error on JSReceiver

---

metaapp/src/androidTest/java/com/sourcepointmeta/metaapp/MetaAppTests.java
metaapp/src/androidTest/java/com/sourcepointmeta/metaapp/MetaAppValidationTests.java
metaapp/src/androidTest/java/com/sourcepointmeta/metaapp/Utility.java

corrected package name in import line for SplashScreenActivity

[SP-4434] corrected package name while importing SplashScreenActivity

---

cmplibrary/src/main/res/raw/js_receiver.js

Fixed timeout error on lower version of android

SP-4619 Fixed syntax error on js_receiver file

---

app/build.gradle
app/src/androidTest/java/com/sourcepoint/example_app/ExampleAppTests.java
app/src/androidTest/java/com/sourcepoint/example_app/TestData.java
app/src/androidTest/java/com/sourcepoint/example_app/Utility.java

Added 9 E2E native UI test for example app

[SP-4556] Implemented native UI tests for example app

---

cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/GDPRConsentLib.java
cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/NativeMessageAttrs.java
cmplibrary/src/test/java/com/sourcepoint/gdpr_cmplibrary/NativeMessageAttrsTest.java

Instead of catching only ConsentLibException , now catching all Exceptions and wrapping it as ConsentLibException

[SP-4727] catch native message json parsing exceptions

---

app/src/androidTest/java/com/sourcepoint/example_app/ExampleAppTests.java
app/src/androidTest/java/com/sourcepoint/example_app/TestData.java
app/src/androidTest/java/com/sourcepoint/example_app/Utility.java
cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/ConsentAction.java
cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/ConsentWebView.java
cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/GDPRConsentLib.java
cmplibrary/src/main/res/raw/js_receiver.js
cmplibrary/src/test/JS/test_config.js
cmplibrary/src/test/java/com/sourcepoint/gdpr_cmplibrary/ConsentActionTest.java
cmplibrary/src/test/java/com/sourcepoint/gdpr_cmplibrary/GDPRConsentLibTest.java
metaapp/src/androidTest/java/com/sourcepointmeta/metaapp/MetaAppTests.java
metaapp/src/androidTest/java/com/sourcepointmeta/metaapp/TestData.java
metaapp/src/androidTest/java/com/sourcepointmeta/metaapp/Utility.java

Get default PM tab from show pm action from message and UI tests for example app & MetaApp

[SP-4722] Get default PM tab from show pm action

---

cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/ConsentLibBuilder.java
cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/GDPRConsentLib.java
cmplibrary/src/test/java/com/sourcepoint/gdpr_cmplibrary/ConsentLibBuilderTest.java
cmplibrary/src/test/java/com/sourcepoint/gdpr_cmplibrary/GDPRConsentLibTest.java

- Now we have dedicated 'privacy manager' for OTT environment.
- OTT PM will act as first layer message

[SP-5183] Add OTT PM support

---

CHANGELOG.md
README.md
cmplibrary/build.gradle

Prepare for 5.3.10 release

---

.github/workflows/testingMatrix.yml

This workflow will run tests on Android api-level: [30, 29, 28, 27, 26, 25, 24]

[SP-5692] GitHub action for matrix of android apis

---

CHANGELOG.md
README.md
cmplibrary/build.gradle

Prepare 5.3.11

---

cmplibrary/src/main/res/layout/sample_native_message.xml

<br clear="left"/>
<br>
The developer is still supposed to implement their own NativeMessage layout, but this should cause a first impression when trying out the NativeMessage.

slightly improve native message layout

---

cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/ConsentLibBuilder.java
cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/GDPRConsentLib.java
cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/SourcePointClient.java
cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/SourcePointClientConfig.java
cmplibrary/src/test/java/com/sourcepoint/gdpr_cmplibrary/ConsentLibBuilderTest.java
cmplibrary/src/test/java/com/sourcepoint/gdpr_cmplibrary/GDPRConsentLibTest.java
cmplibrary/src/test/java/com/sourcepoint/gdpr_cmplibrary/SourcePointClientTest.java
samples/app/src/main/java/com/sourcepoint/example_app/MainActivity.java
samples/authexample/src/main/java/com/example/authexample/ConsentManager.java
samples/metaapp/src/main/java/com/sourcepointmeta/metaapp/ui/ConsentViewActivity.java
samples/metaapp/src/main/java/com/sourcepointmeta/metaapp/ui/NewPropertyActivity.java

Rename run() to loadMessage() and showPm() to loadPrivacyManager().

[SP-5780] Refactor consentlib methods name.

---

cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/ConsentLibBuilder.java
cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/GDPRConsentLib.java
cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/SourcePointClient.java
cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/SourcePointClientConfig.java
cmplibrary/src/test/java/com/sourcepoint/gdpr_cmplibrary/ConsentLibBuilderTest.java
cmplibrary/src/test/java/com/sourcepoint/gdpr_cmplibrary/GDPRConsentLibTest.java
cmplibrary/src/test/java/com/sourcepoint/gdpr_cmplibrary/SourcePointClientTest.java
samples/app/src/main/java/com/sourcepoint/example_app/MainActivity.java
samples/authexample/src/main/java/com/example/authexample/ConsentManager.java
samples/metaapp/src/main/java/com/sourcepointmeta/metaapp/ui/ConsentViewActivity.java
samples/metaapp/src/main/java/com/sourcepointmeta/metaapp/ui/NewPropertyActivity.java

Reverts SourcePointUSA/android-cmp-app#309

Revert "[SP-5780] Refactor consentlib methods name."

---

cmplibrary/src/androidTest/java/com/sourcepoint/cmplibrary/SpUtilsTest.kt
cmplibrary/src/androidTest/java/com/sourcepoint/cmplibrary/campaign/CampaignManagerImplTest.kt
cmplibrary/src/androidTest/java/com/sourcepoint/cmplibrary/creation/delegate/SpConsentLibDelegateTest.kt
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/consent/ConsentManager.kt
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/creation/SpConfigDataBuilder.kt
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/model/exposed/SpConfig.kt
cmplibrary/src/test/java/com/sourcepoint/cmplibrary/campaign/CampaignManagerTest.kt
cmplibrary/src/test/java/com/sourcepoint/cmplibrary/creation/BuilderTest.kt
cmplibrary/src/test/java/com/sourcepoint/cmplibrary/creation/FactoryKtTest.kt
cmplibrary/src/test/java/com/sourcepoint/cmplibrary/creation/SpCmpBuilderTest.kt
cmplibrary/src/test/java/com/sourcepoint/cmplibrary/creation/SpConfigDataBuilderTest.kt
cmplibrary/src/test/java/com/sourcepoint/cmplibrary/exception/ErrorMessageManagerImplTest.kt
samples/app/src/androidTest/java/com/sourcepoint/app/v6/MainActivityKotlinTest.kt

[SP-6966] SpConfigDataBuilder unit-tests
[SP-6965] SpCmpBuilder unit-tests
[SP-6966]: https://sourcepoint.atlassian.net/browse/SP-6966
[SP-6965]: https://sourcepoint.atlassian.net/browse/SP-6965

[SP-6964] ConsentManager unit-tests

---

cmplibrary/src/androidTest/java/com/sourcepoint/cmplibrary/creation/delegate/SpConsentLibDelegateTest.kt
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/SpClient.kt
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/SpConsentLibImpl.kt
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/consent/ConsentManager.kt
cmplibrary/src/test/java/com/sourcepoint/cmplibrary/consent/ConsentManagerImplTest.kt
samples/app/src/main/java/com/sourcepoint/app/v6/MainActivityJava.java
samples/app/src/main/java/com/sourcepoint/app/v6/MainActivityKotlin.kt
samples/app/src/main/java/com/sourcepoint/app/v6/OnlyGdprKotlin.kt
samples/metaapp/src/androidTest/java/com/sourcepointmeta/metaapp/TestUseCaseMeta.kt
samples/metaapp/src/main/java/com/sourcepointmeta/metaapp/ui/demo/DemoActivity.kt

This reverts commit 6abb409daa3c4eb0fa3e49b0bb48295ee7d03b2d.

[SP-7688] Revert "[SP-7618] Consent flag for pm (#406)"

---

README.md

[HCD-215] Added doc for the clearAllData method

---

build.gradle
buildSrc/src/main/kotlin/Versions.kt
cmplibrary/src/androidTest/java/com/sourcepoint/cmplibrary/SpUtilsTest.kt
ui-test-util/jsonFiles/unified_wrapper_resp/response_gdpr_and_ccpa_apply_false.json
ui-test-util/jsonFiles/unified_wrapper_resp/response_gdpr_and_ccpa_apply_true.json

[SP-7591] Regression tests  for the functions ccpaApplies and gdprApplies

---

README.md

Clarify OTT PM surface and resurface

Clarify OTT PM surface and resurface in README.md

---

README.md

Reverts SourcePointUSA/android-cmp-app#486

Revert "[HCD-197] Add event callback descriptions"

---

MIGRATION_GUIDE.md

toggle multi-campaign on app property in portal

[HCD-303] Update migration guide with enabling multi-campaign toggle

---

cmplibrary/src/main/java/com/sourcepoint/cmplibrary/SpConsentLibImpl.kt
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/campaign/CampaignManager.kt
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/data/network/model/MessageModelRespExt.kt
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/model/MessageModelResp.kt

Reverts SourcePointUSA/android-cmp-app#546

Revert "[DIA-1302] Issue with Resurfacing the OTT Privacy Manager on AndroidTV"

---

README.md

Google additional consent string is stored in IABTCF_AddtlConsent in user local storage

[HCD-327] Google Additional Consent

---

cmplibrary/src/main/java/com/sourcepoint/cmplibrary/SpConsentLibImpl.kt

[DIA-1988] Call the custom-metrics for incoming errors from the RendringApp

---

cmplibrary/src/main/java/com/sourcepoint/cmplibrary/model/exposed/SPConsents.kt

Reverts SourcePointUSA/android-cmp-app#635

Revert "[DIA-2106] Make UUID public on CCPAConsent"

---

cmplibrary/src/main/java/com/sourcepoint/cmplibrary/core/web/ConsentWebView.kt
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/data/ServiceImpl.kt
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/data/network/model/MessageModelReqExt.kt
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/data/network/model/optimized/ConsentStatusApiModel.kt
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/data/network/model/optimized/ConsentStatusApiModelExt.kt
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/data/network/model/optimized/MessagesApiModel.kt
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/data/network/model/optimized/MessagesApiModelExt.kt
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/data/network/model/optimized/PostChoiceApiModelExt.kt
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/data/network/util/HttpUrlManager.kt
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/model/MessageModelReq.kt
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/model/exposed/SPConsents.kt
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/util/extensions/WebViewExt.kt
cmplibrary/src/test/java/com/sourcepoint/cmplibrary/data/network/util/HttpUrlManagerTest.kt
cmplibrary/src/test/java/com/sourcepoint/cmplibrary/util/SpUtilsTest.kt
samples/app/src/androidTest/java/com/sourcepoint/app/v6/TestData.kt
samples/app/src/androidTest/java/com/sourcepoint/app/v6/TestUseCase.kt
samples/app/src/androidTest/java/com/sourcepoint/app/v6/web/WebConsentTransferTestActivityTest.kt
samples/app/src/main/AndroidManifest.xml
samples/app/src/main/java/com/sourcepoint/app/v6/MainActivityKotlin.kt
samples/app/src/main/java/com/sourcepoint/app/v6/web/WebConsentTransferTestActivity.kt
samples/app/src/main/res/layout/activity_main_v7.xml
samples/app/src/main/res/layout/activity_web_consent_transfer_test.xml
samples/app/src/main/res/values/strings.xml
ui-test-util/src/main/java/com/example/uitestutil/EspressoUtils.kt

Jira - https://sourcepoint.atlassian.net/browse/DIA-1806
This PR introduces public API for the users to transfer their consent (`SPConsent` instance from either `onSpFinished` or `onConsentReady` callbacks) to the webview.

[DIA-1806] Implement consent transfer to Webview

---

cmplibrary/src/test/java/com/sourcepoint/cmplibrary/campaign/CampaignManagerTest.kt
cmplibrary/src/test/java/com/sourcepoint/cmplibrary/data/ServiceImplTest.kt

Task
Jira - https://sourcepoint.atlassian.net/browse/DIA-2243
Description
This PR introduces unit tests that cover the case of updating uspstring locally in the data storage.

[DIA-2243] Add tests to verify uspstring is being updated in the DataStorage

---

README.md

JIRA Ticket - https://sourcepoint.atlassian.net/browse/DIA-2263
Description
This PR introduces release documentation transfer from a `README.md` file into the according confluence page.

[DIA-2263] Create confluence page for the SDK release process

---

cmplibrary/src/main/java/com/sourcepoint/cmplibrary/SpClient.kt
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/consent/ClientEventManager.kt

These changes help Unity SDK to communicate with native Android SDK

[DIA-1961] Extended UnitySpClient for actual Unity v7 port

---

cmplibrary/src/main/java/com/sourcepoint/cmplibrary/data/network/model/optimized/ConsentStatusApiModelExt.kt
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/model/exposed/SPConsents.kt
samples/app/src/androidTest/java/com/sourcepoint/app/v6/MainActivityKotlinTest.kt

Reverts SourcePointUSA/android-cmp-app#724

Revert "[DIA-2918] Consentstatus missing"

---

cmplibrary/src/main/java/com/sourcepoint/cmplibrary/consent/ConsentManager.kt
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/data/Service.kt
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/data/ServiceImpl.kt

JIRA - [DIA-3017](https://sourcepoint.atlassian.net/browse/DIA-3017)
[DIA-3017]: https://sourcepoint.atlassian.net/browse/DIA-3017?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DIA-3017] Add the `UsNat` consent object in the callbacks

---

README.md

Jira - [DIA-2913](https://sourcepoint.atlassian.net/browse/DIA-2913)
[DIA-2913]: https://sourcepoint.atlassian.net/browse/DIA-2913?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DIA-2913] Update README file to highlight the migration to the Jetpack DataStore

---

cmplibrary/src/main/java/com/sourcepoint/cmplibrary/data/network/model/optimized/ConsentStatusApiModel.kt

https://sourcepoint.atlassian.net/browse/DIA-3710

[DIA-3710] Add property `EMPTY_VL` to the `GranularState`

---

.github/workflows/feature-tests.yml
.github/workflows/instrumentation_tests.yml
.github/workflows/metaap_instrumentation_tests.yml
.github/workflows/release-testing.yml
.github/workflows/release.yml
.github/workflows/test.yml
build.gradle
cmplibrary/build.gradle.kts
cmplibrary/src/androidTest/AndroidManifest.xml
cmplibrary/src/main/AndroidManifest.xml
gradle.properties
gradle/wrapper/gradle-wrapper.properties
samples/app/build.gradle
samples/metaapp/build.gradle.kts
samples/metaapp/src/main/java/com/sourcepointmeta/metaapp/App.kt
samples/native-message-demo/build.gradle
samples/ott-message-demo/build.gradle
samples/web-message-demo/build.gradle
ui-test-util/build.gradle

Updating project dependencies, such as AGP version, Gradle version, third-party libraries versions, etc. gradually.
[DIA-3574](https://sourcepoint.atlassian.net/browse/DIA-3574)
[DIA-3574]: https://sourcepoint.atlassian.net/browse/DIA-3574?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DIA-3574] Update SDK dependencies V1

---

cmplibrary/src/main/java/com/sourcepoint/cmplibrary/model/MessageLanguage.kt

https://sourcepoint.atlassian.net/browse/DIA-3945

[DIA-3945] Add Tagalog to CMP

---

cmplibrary/src/main/java/com/sourcepoint/cmplibrary/SpConsentLibImpl.kt
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/consent/ClientEventManager.kt

Fixes an issue causing the PM being reloaded when the user takes taps on dismiss, when the PM is used as 1st layer message.

DIA-4092 fix PM dismiss button for 1st layer PMs

---

build.gradle
buildSrc/src/main/kotlin/Versions.kt
cmplibrary/build.gradle.kts
cmplibrary/gradle.properties
gradleutils/ktlint_utils.gradle
gradleutils/test_config.gradle
samples/app/build.gradle
samples/app/src/androidTest/java/com/sourcepoint/app/v6/TestUseCase.kt
samples/metaapp/build.gradle.kts
samples/nat-message-demo/build.gradle
samples/ott-message-demo/build.gradle
samples/web-message-demo/build.gradle
scripts/publish-mavencentral.gradle
ui-test-util/build.gradle

* update core-module to 0.0.7 (with updated ktor version)
* update coroutines and serialization dependencies
* fix minor build warnings

Release 7.11.0 rc1

---

cmplibrary/build.gradle.kts

* this fixed an issue with GCMStatuses being null

DIA-5149 update mobile-core to 0.0.10

---

cmplibrary/src/main/java/com/sourcepoint/cmplibrary/model/MessageLanguage.kt

Added  
Galician, Arabic, Basque and Bosnian

Add Galician, Arabic, Basque and Bosnian

---

cmplibrary/build.gradle.kts
cmplibrary/src/main/assets/js_receiver.js
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/creation/Factory.kt
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/data/network/util/CampaignType.kt
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/mobile_core/SPConsentWebView.kt
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/model/exposed/SPConsents.kt
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/util/SpUtils.kt
samples/app/src/main/java/com/sourcepoint/app/v6/MainActivityKotlin.kt
samples/app/src/main/java/com/sourcepoint/app/v6/di/AppModule.kt

[DIA-5360](https://sourcepoint.atlassian.net/browse/DIA-5360) [Android] integrate mobile-core with preferences
[DIA-5360]: https://sourcepoint.atlassian.net/browse/DIA-5360?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DIA-5360 integrate preferences

---

cmplibrary/build.gradle.kts
cmplibrary/src/main/java/com/sourcepoint/cmplibrary/model/exposed/SPConsents.kt

Waiting on https://github.com/SourcePointUSA/mobile-core/pull/76 to be merged

DIA-5922 add `versionId` to preferences consent status
